"""N-E — prioritised forward research findings with real, falsifiable hypotheses.

WHAT THIS IS. A deterministic derivation of research FINDINGS from evidence the system
actually measures: the market-phase assessment, spot turnover shares, sector breadth and
concentration, participant cohorts and the scenario provider's band. Each candidate
carries a hypothesis, the exact forward condition that would CONFIRM it, the condition
that would INVALIDATE it, and a horizon after which an unresolved finding expires.

WHAT THIS IS NOT. It is not a news feed relabelled as research, and it is not an opinion
from the language model. No text here is generated by an LLM and no number here is
invented: every figure is passed through from the measuring layer with its own provenance.

HOW OUTCOME HISTORY BECOMES REAL. Each candidate declares a MACHINE-CHECKABLE measure
(`measure.name`) plus a comparison. The caller persists the finding once, then re-measures
it on every refresh, so the record accumulates observations and eventually resolves to
CONFIRMED, INVALIDATED or EXPIRED_UNRESOLVED. The original hypothesis is never rewritten
when the reading moves — that is the whole point of keeping the record.
"""
from . import meta as M

RESEARCH_RULE_VERSION = 'research-findings-v1'

# Priority ladder from the spec. Deliberately NOT a score: "avoid for now" and
# "insufficient evidence" are different answers, and neither is a weak "watch".
AVOID = 'AVOID_FOR_NOW'
PAPER_TEST = 'CONSIDER_PAPER_TEST'
INVESTIGATE = 'INVESTIGATE'
WATCH = 'WATCH'
INSUFFICIENT = 'INSUFFICIENT_EVIDENCE'
PRIORITY_ORDER = {AVOID: 0, PAPER_TEST: 1, INVESTIGATE: 2, WATCH: 3, INSUFFICIENT: 4}
PRIORITY_LABEL = {
    AVOID: 'Avoid for now',
    PAPER_TEST: 'Consider a paper test',
    INVESTIGATE: 'Investigate',
    WATCH: 'Watch',
    INSUFFICIENT: 'Insufficient evidence',
}

# Comparison operators a stored finding may be re-checked with.
GTE = 'GTE'
LTE = 'LTE'
RANGE_AT_HORIZON = 'RANGE_AT_HORIZON'

# What the ABSENCE of a candidate means on a later refresh.
ABSENT_INVALIDATES = 'INVALIDATED'
ABSENT_NO_OBSERVATION = 'NO_OBSERVATION'


def _f(v):
    try:
        return None if v is None else float(v)
    except Exception:  # noqa
        return None


def _pc(v, places=1):
    v = _f(v)
    return None if v is None else round(v * 100, places)


def _cand(key, *, title, hypothesis, priority, knowledge_type, measure_name, measure_unit,
          measure_value, confirm, invalidate, horizon_days, min_hold_days=3,
          evidence_refs=None, limitations=None, as_of=None, inputs=None,
          absent_means=ABSENT_NO_OBSERVATION, deep_link=None):
    """One candidate finding. `hypothesis` is the sentence that gets frozen on open."""
    return {
        'key': key,
        'ruleVersion': RESEARCH_RULE_VERSION,
        'title': title,
        'hypothesis': hypothesis,
        'priority': priority,
        'priorityLabel': PRIORITY_LABEL.get(priority, priority),
        'knowledgeType': knowledge_type,
        'measure': {'name': measure_name, 'unit': measure_unit, 'value': measure_value},
        'confirmIf': confirm,
        'invalidateIf': invalidate,
        'horizonDays': horizon_days,
        'minHoldDays': min_hold_days,
        'absentMeans': absent_means,
        'evidenceRefs': list(evidence_refs or []),
        'limitations': list(limitations or []),
        'inputs': inputs or {},
        'asOf': as_of,
        'deepLink': deep_link,
    }


def _cond(op, threshold, text, *, lower=None, upper=None):
    return {'op': op, 'threshold': threshold, 'lower': lower, 'upper': upper, 'text': text}


# ---------------------------------------------------------------------------
# Generators. Each one returns zero or one candidate and refuses to speak when
# its own input is not FRESH enough to carry a hypothesis.
# ---------------------------------------------------------------------------
def _from_phase(ph):
    if not ph:
        return None
    phase = ph.get('phase')
    inp = ph.get('inputs') or {}
    breadth = _f(inp.get('breadth'))
    spread = _f(inp.get('spreadPct'))
    refs = list(ph.get('evidenceRefs') or [])
    lims = list(ph.get('limitations') or [])[:3]
    if ph.get('status') not in (M.FRESH, M.PARTIAL) or phase in (None, M.UNKNOWN):
        return _cand(
            'market-leadership', title='Market leadership is not readable right now',
            hypothesis=('Leadership between Bitcoin and the rest of the market cannot be '
                        'assessed from the current universe, so no leadership hypothesis is '
                        'offered. This is an absence of evidence, not a neutral reading.'),
            priority=INSUFFICIENT, knowledge_type=M.UNKNOWN_KIND,
            measure_name='phase.breadth', measure_unit='ratio', measure_value=breadth,
            confirm=None, invalidate=None, horizon_days=7,
            evidence_refs=refs, limitations=lims, as_of=ph.get('asOf'),
            inputs=inp, absent_means=ABSENT_NO_OBSERVATION)
    if breadth is None:
        return None
    if phase == M.ALTCOIN_LED:
        return _cand(
            'market-leadership', title='Breadth says the move is led by altcoins, not Bitcoin',
            hypothesis=('%s Hypothesis: this is a broad rotation rather than a one-week '
                        'artefact, and altcoin breadth stays above 60%% of the eligible '
                        'universe for at least three more days.' % (ph.get('finding') or '')),
            priority=INVESTIGATE, knowledge_type=M.SYSTEM_ASSESSMENT,
            measure_name='phase.breadth', measure_unit='ratio', measure_value=breadth,
            confirm=_cond(GTE, 0.60, 'Altcoin breadth is still at or above 60% after three days.'),
            invalidate=_cond(LTE, 0.40, 'Breadth falls to 40% or below — leadership has returned to Bitcoin.'),
            horizon_days=14, evidence_refs=refs,
            limitations=lims + ['Breadth is measured over the documented eligible universe '
                                'only and says nothing about market capitalisation or '
                                'turnover. It is an observation, not a permission to trade.'],
            as_of=ph.get('asOf'), inputs=inp, absent_means=ABSENT_INVALIDATES)
    if phase == M.BTC_LED:
        return _cand(
            'market-leadership', title='Breadth says Bitcoin is leading, not the altcoins',
            hypothesis=('%s Hypothesis: Bitcoin keeps leadership and altcoin breadth stays at '
                        'or below 40%% of the eligible universe for at least three more days.'
                        % (ph.get('finding') or '')),
            priority=INVESTIGATE, knowledge_type=M.SYSTEM_ASSESSMENT,
            measure_name='phase.breadth', measure_unit='ratio', measure_value=breadth,
            confirm=_cond(LTE, 0.40, 'Altcoin breadth is still at or below 40% after three days.'),
            invalidate=_cond(GTE, 0.60, 'Breadth rises to 60% or above — the altcoins have taken leadership.'),
            horizon_days=14, evidence_refs=refs, limitations=lims,
            as_of=ph.get('asOf'), inputs=inp, absent_means=ABSENT_INVALIDATES)
    # MIXED
    return _cand(
        'market-leadership', title='Leadership is genuinely mixed — no rotation call is justified',
        hypothesis=('%s Hypothesis: neither side has leadership, so a rotation trade has no '
                    'breadth support until breadth leaves the 40–60%% band.'
                    % (ph.get('finding') or '')),
        priority=WATCH, knowledge_type=M.SYSTEM_ASSESSMENT,
        measure_name='phase.breadth', measure_unit='ratio', measure_value=breadth,
        confirm=None,
        invalidate=None,
        horizon_days=10, evidence_refs=refs,
        limitations=lims + ['"Mixed" is a real result, not a missing one. A spread of %s '
                            'points is inside the rule\u2019s indecision band.'
                            % (spread if spread is not None else '?')],
        as_of=ph.get('asOf'), inputs=inp, absent_means=ABSENT_NO_OBSERVATION)


def _from_volume(vol):
    if not vol:
        return None
    w = ((vol.get('windows') or {}).get('24h') or {})
    alt = _f(w.get('altShare'))
    if alt is None or w.get('status') not in (M.FRESH, M.PARTIAL):
        return None
    longer = ((vol.get('windows') or {}).get('7d') or {})
    partial_note = ('The 7-day and 30-day windows are still PARTIAL (%s of %s days stored), '
                    'so no multi-day turnover trend can be claimed yet.'
                    % (longer.get('daysCovered'), longer.get('daysRequired')))
    return _cand(
        'turnover-rotation',
        title='Non-Bitcoin assets are taking the larger share of measured spot turnover',
        hypothesis=('Non-Bitcoin assets took %.1f%% of measured USD-equivalent spot turnover '
                    'over the last 24 hours (Bitcoin %.1f%%). Hypothesis: money is genuinely '
                    'rotating, and the non-Bitcoin share holds at or above 55%% for at least '
                    'three more days.' % (_pc(alt), _pc(w.get('btcShare')) or 0.0))
        if alt >= 0.55 else
        ('Bitcoin took %.1f%% of measured USD-equivalent spot turnover over the last 24 hours. '
         'Hypothesis: turnover stays Bitcoin-weighted and the non-Bitcoin share stays below '
         '55%% for at least three more days.' % (_pc(w.get('btcShare')) or 0.0)),
        priority=WATCH, knowledge_type=M.OBSERVED_FACT,
        measure_name='volume.altShare24h', measure_unit='ratio', measure_value=alt,
        confirm=(_cond(GTE, 0.55, 'The non-Bitcoin turnover share is still at or above 55% after three days.')
                 if alt >= 0.55 else
                 _cond(LTE, 0.55, 'The non-Bitcoin turnover share is still below 55% after three days.')),
        invalidate=(_cond(LTE, 0.45, 'The non-Bitcoin share drops to 45% or below — the rotation stalled.')
                    if alt >= 0.55 else
                    _cond(GTE, 0.60, 'The non-Bitcoin share rises to 60% or above — turnover rotated away from Bitcoin.')),
        horizon_days=10,
        evidence_refs=[M.evidence_ref('turnover', vol.get('universeSnapshotId'), '24h')],
        limitations=[partial_note,
                     'Spot turnover share only. Derivatives volume and market-capitalisation '
                     'dominance are different measures and are not mixed in.',
                     'Turnover is activity, not net capital flow: a dollar can change hands '
                     'many times in a day.'],
        as_of=w.get('asOf'),
        inputs={'btcShare': w.get('btcShare'), 'altShare': w.get('altShare'),
                'totalTurnoverUsd': w.get('totalTurnoverUsd')},
        absent_means=ABSENT_NO_OBSERVATION)


def _from_sectors(sec):
    """Every concentrated sector is a CAUTION finding, never a leadership call. All of
    them are emitted (not just the most concentrated) so a finding cannot disappear —
    and therefore be recorded as invalidated — merely because another sector overtook it
    in one refresh."""
    if not sec:
        return []
    rows = [r for r in (sec.get('sectors') or []) if r.get('concentrated')]
    rows.sort(key=lambda r: _f(r.get('turnoverConcentration')) or 0, reverse=True)
    out = []
    for r in rows[:3]:
        conc = _f(r.get('turnoverConcentration'))
        if conc is None:
            continue
        out.append(_cand(
            'sector-concentration:%s' % r.get('sector'),
            title='%s looks strong, but the move is one token' % r.get('sector'),
            hypothesis=('%.0f%% of %s sector turnover sits in %s, so the sector reading is a '
                        'single-token move rather than broad sector leadership. Hypothesis: it '
                        'stays concentrated (at or above 60%%) rather than broadening out.'
                        % (_pc(conc, 0), r.get('sector'), r.get('largestMember'))),
            priority=AVOID, knowledge_type=M.OBSERVED_FACT,
            measure_name='sector.%s.turnoverConcentration' % r.get('sector'),
            measure_unit='ratio', measure_value=conc,
            confirm=_cond(GTE, 0.60, 'Turnover is still 60% or more concentrated in one token after three days.'),
            invalidate=_cond(LTE, 0.40, 'Concentration falls to 40% or below — participation genuinely broadened.'),
            horizon_days=14, evidence_refs=list(r.get('evidenceRefs') or []),
            limitations=[l for l in [r.get('limitation')] if l] +
                        ['The taxonomy (%s) is single-label and covers only mapped assets, so '
                         'sector figures do not add up to the whole market.'
                         % sec.get('ruleVersion'),
                         'A concentrated sector is labelled concentrated, never "leading".'],
            as_of=sec.get('asOf'),
            inputs={'sector': r.get('sector'), 'largestMember': r.get('largestMember'),
                    'strength': r.get('strength'), 'participation': r.get('participation'),
                    'membersWithData': r.get('membersWithData')},
            absent_means=ABSENT_INVALIDATES))
    return out


def _from_participants(parts):
    """One cohort finding, and only where the cohort reported a directional, countable
    fact. Miner behaviour is deliberately reported as insufficient evidence."""
    out = []
    rows = (parts or {}).get('participants') or []
    by_name = {(r.get('participant') or '').upper(): r for r in rows}
    etf = by_name.get('ETFS') or by_name.get('ETF')
    if etf and etf.get('status') in (M.FRESH, M.STALE, M.PARTIAL):
        d = etf.get('detail') or {}
        days = d.get('consecutiveDays')
        flow = _f(d.get('netFlowUsdMillions'))
        if days is not None and flow is not None and abs(flow) > 0:
            inflow = flow > 0
            out.append(_cand(
                'etf-flow-streak',
                title='US spot Bitcoin ETFs are in a reported %s streak'
                      % ('inflow' if inflow else 'outflow'),
                hypothesis=('%s Hypothesis: the streak persists and reaches at least %d '
                            'consecutive reporting days before it breaks.'
                            % (etf.get('finding') or '', int(days) + 2)),
                priority=WATCH, knowledge_type=M.REPORTED_FACT,
                measure_name='etf.consecutiveDays', measure_unit='days',
                measure_value=_f(days),
                confirm=_cond(GTE, float(int(days) + 2),
                              'The streak reaches %d or more consecutive reporting days.'
                              % (int(days) + 2)),
                invalidate=_cond(LTE, 1.0,
                                 'The streak breaks — a reporting day lands the other way.'),
                horizon_days=14, min_hold_days=1,
                evidence_refs=list(etf.get('evidenceRefs') or []),
                limitations=[l for l in [etf.get('limitation')] if l] +
                            ['Reported, not observed: these are issuer-published daily '
                             'figures with a lag, not a sub-daily flow measurement.',
                             'ETF flows are one cohort. They must not be re-used as a '
                             'second, independent institutional signal.'],
                as_of=etf.get('asOf'), inputs=d,
                absent_means=ABSENT_NO_OBSERVATION))
    miners = by_name.get('MINERS')
    if miners is None or miners.get('status') == M.UNSUPPORTED:
        out.append(_cand(
            'miner-holdings', title='Miner behaviour cannot be researched here',
            hypothesis=('No miner wallet-classification dataset is connected, so miner '
                        'selling or accumulation cannot be measured. Hashrate is a network '
                        'statistic, not holdings evidence, and is not substituted for one.'),
            priority=INSUFFICIENT, knowledge_type=M.UNKNOWN_KIND,
            measure_name='miners.holdings', measure_unit='none', measure_value=None,
            confirm=None, invalidate=None, horizon_days=30,
            evidence_refs=[], limitations=['UNSUPPORTED / NO_MINER_HOLDINGS_COVERAGE.'],
            as_of=(parts or {}).get('asOf'), inputs={},
            absent_means=ABSENT_NO_OBSERVATION))
    return out


def _from_scenario(sc):
    """The scenario band is a forward, falsifiable statement: either the realised price
    lands inside the band at the horizon or it does not. That makes it the single most
    honest research finding available here."""
    if not sc or not sc.get('available'):
        return None
    lo, hi = _f(sc.get('lowerPct')), _f(sc.get('upperPct'))
    lo_p, hi_p = _f(sc.get('lowerPrice')), _f(sc.get('upperPrice'))
    if None in (lo, hi, lo_p, hi_p):
        return None
    skew = hi + lo
    asset = sc.get('assetId') or 'BTC'
    horizon = int(sc.get('horizonDays') or 7)
    tilt = ('tilted to the upside' if skew >= 1.0 else
            'tilted to the downside' if skew <= -1.0 else 'close to symmetric')
    tilt_short = ('an upside-tilted' if skew >= 1.0 else
                  'a downside-tilted' if skew <= -1.0 else 'a near-symmetric')
    return _cand(
        'scenario-band:%s:%dd' % (asset, horizon),
        title='Comparable past %s conditions produced %s range' % (asset, tilt_short),
        hypothesis=('Comparable past conditions produced %+.1f%% to %+.1f%% for %s over %d '
                    'days — a range %s. Hypothesis: the realised %d-day move lands inside '
                    'that band (%s to %s).'
                    % (lo, hi, asset, horizon, tilt, horizon,
                       ('%.2f' % lo_p), ('%.2f' % hi_p))),
        priority=(PAPER_TEST if abs(skew) >= 1.0 else WATCH),
        knowledge_type=M.SYSTEM_ASSESSMENT,
        measure_name='asset.%s.price' % asset, measure_unit='usd',
        measure_value=_f(sc.get('anchorPrice')),
        confirm=_cond(RANGE_AT_HORIZON, None,
                      'At the horizon the observed price is inside the band.',
                      lower=lo_p, upper=hi_p),
        invalidate=_cond(RANGE_AT_HORIZON, None,
                         'At the horizon the observed price is outside the band.',
                         lower=lo_p, upper=hi_p),
        horizon_days=horizon, min_hold_days=horizon,
        evidence_refs=[r for r in [sc.get('snapshotId'), sc.get('evaluationRef')] if r],
        limitations=['This is a HISTORICAL SCENARIO RANGE, not a forecast. The middle of '
                     'the band is not an expectation and carries no measured skill.',
                     'A move beyond either edge of the band remains possible; the band '
                     'covered the realised outcome %s of the time in walk-forward testing.'
                     % (('%.1f%%' % (_pc(sc.get('coverageRate')) or 0))
                        if sc.get('coverageRate') is not None else 'an unmeasured share')],
        as_of=sc.get('anchorDate'), inputs={'lowerPct': lo, 'upperPct': hi,
                                            'lowerPrice': lo_p, 'upperPrice': hi_p,
                                            'anchorPrice': sc.get('anchorPrice'),
                                            'modelVersion': sc.get('modelVersion')},
        deep_link=sc.get('evidenceDeepLink'),
        absent_means=ABSENT_NO_OBSERVATION)


def derive(*, phase=None, volume=None, sectors=None, participants=None, scenario=None):
    """All candidate findings for right now, highest priority first."""
    cands = []
    for gen, arg in ((_from_phase, phase), (_from_volume, volume),
                     (_from_scenario, scenario)):
        try:
            c = gen(arg)
        except Exception:  # noqa
            c = None
        if c:
            cands.append(c)
    for gen, arg in ((_from_sectors, sectors), (_from_participants, participants)):
        try:
            cands.extend(gen(arg) or [])
        except Exception:  # noqa
            pass
    cands.sort(key=lambda c: (PRIORITY_ORDER.get(c['priority'], 9), c['key']))
    return cands


def measured_domains(*, phase=None, volume=None, sectors=None, participants=None,
                     scenario=None):
    """Which input domains were actually MEASURABLE on this pass.

    This matters enormously for outcome history: a finding must never be recorded as
    invalidated because its input feed was cold. Absence of evidence is not evidence of
    a changed market, so the caller only honours "absence invalidates" for a domain that
    genuinely produced a reading.
    """
    ok = set()
    live = (M.FRESH, M.PARTIAL, M.STALE)
    if (phase or {}).get('status') in live and (phase or {}).get('phase') not in (None, M.UNKNOWN):
        ok.add('phase')
    if (((volume or {}).get('windows') or {}).get('24h') or {}).get('status') in live:
        ok.add('volume')
    if ((sectors or {}).get('status') in live and (sectors or {}).get('sectors')
            and ((sectors or {}).get('sectorsWithBreadth') or 0) > 0):
        ok.add('sectors')
    if (participants or {}).get('status') in live:
        ok.add('participants')
    if (scenario or {}).get('available'):
        ok.add('scenario')
    return ok


KEY_DOMAINS = (('market-leadership', 'phase'), ('turnover-rotation', 'volume'),
               ('sector-concentration', 'sectors'), ('etf-flow-streak', 'participants'),
               ('miner-holdings', 'participants'), ('scenario-band', 'scenario'))


def domain_for(key):
    for prefix, dom in KEY_DOMAINS:
        if str(key or '').startswith(prefix):
            return dom
    return None


def evaluate_condition(cond, value, *, observed_price=None):
    """True when the stored condition is met by the new measurement. Never guesses: a
    missing value or a malformed condition is simply 'not met'."""
    if not cond:
        return False
    op = cond.get('op')
    if op == RANGE_AT_HORIZON:
        p = _f(observed_price if observed_price is not None else value)
        lo, hi = _f(cond.get('lower')), _f(cond.get('upper'))
        if None in (p, lo, hi):
            return False
        return lo <= p <= hi
    v, t = _f(value), _f(cond.get('threshold'))
    if v is None or t is None:
        return False
    if op == GTE:
        return v >= t
    if op == LTE:
        return v <= t
    return False
